import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import jordidev from "../public/jordi-image.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import { useState } from "react";
import { Stack, Switch, Typography } from "@mui/material";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const newTab = (url) => {
    window.open(url, "_blank");
  };
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jordi Romero Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-50">TheJorko</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl text-gray-600 dark:text-gray-100"
                />
              </li>
              <li className="ml-10">
                <Stack direction="row" spacing={1} alignItems="center">
                  <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-100  max-w-lg mx-auto">
                    En
                  </p>
                  <Switch defaultChecked />
                  <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-100  max-w-lg mx-auto">
                    Es
                  </p>
                </Stack>
              </li>
            </ul>
          </nav>
          <div className="relative mx-auto w-50 h-50 overflow-hidden md:h-80 md:w-80">
            <Image src={jordidev} alt="jordidev" className="rounded-full" />
          </div>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jordi Romero
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-600 dark:text-gray-100">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400 md:text-xl max-w-lg mx-auto">
              I'm Jordi Romero, graduated in Computer Engineering, fan of
              videogames for as long as I can remember and a cat person.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillGithub
              className="cursor-pointer dark:text-gray-100"
              onClick={() => newTab("https://github.com/JRomeroSuarez")}
            />
            <AiFillLinkedin
              className="cursor-pointer dark:text-gray-100"
              onClick={() =>
                newTab("https://www.linkedin.com/in/jordi-romero-295976180/")
              }
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-100">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Computing has always been an important part of my life and I think
              that the path I have chosen has allowed me to go deeper into
              learning both software and hardware.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              My main hobby is video games as they have accompanied me in every
              stage of my life. Narrative games, multiplayer, RPG, I don't have
              any preference. But the game that no matter how many times I leave
              it, I always come back is Destiny 2, which I enjoy a lot with
              friends.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              But I don't spend all day playing. I also like to play sports. For
              many years I played in the basketball team in my city and this
              last year I've been hitting the gym to clear my mind and stretch
              my body.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Lastly, I also love cinema, both commercial films and Saturday
              afternoon movies.
            </p>
          </div>

          <div>
            <h3 className="text-3xl py-1 mt-10 dark:text-gray-100">
              Companies that I've worked
            </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800">
              <h3 className="text-2xl font-medium pb-2 dark:text-gray-100">
                Universal Doctor
              </h3>
              <ul>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Maquetación con la librería MaterialUI con referencia a
                  diseños en AdobeXD y Figma
                </li>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Desarrollo del flujo completo de aplicaciones para la creación
                  de estudios médicos y análisis de sus datos
                </li>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Mantenimiento de aplicaciones ya publicadas
                </li>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Implementación del sistema CI/CD
                </li>
              </ul>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-800">
              <h3 className="text-2xl font-medium pb-2 dark:text-gray-100">
                TiMedi
              </h3>
              <ul>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Desarrollo de aplicación web con arquitectura hexagonal para
                  la gestión y administración de SPDs
                </li>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Creación de componentes y maquetación con React/MaterialUI
                </li>
                <li className="text-gray-800 py-1 dark:text-gray-400">
                  Desarrollo de funcionalidades de autenticación a través de
                  aplicaciones de terceros
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 mt-10 dark:text-gray-100">
              Additional Information
            </h3>
            <ul>
              <li>
                <p className="text-lg  py-2  text-gray-400 ">
                  Dominio de HTML, JS, CSS
                </p>
              </li>
              <li>
                <p className="text-lg  py-2  text-gray-400 ">
                  Conocimiento de las bases de datos MySQL, MongoDB
                </p>
              </li>
              <li>
                <p className="text-lg  py-2  text-gray-400 ">
                  Trabajado con frameworks populares de JS como React, NextJS
                </p>
              </li>
              <li>
                <p className="text-lg  py-2  text-gray-400 ">
                  Dominio de las metodologías Agile y SCRUM
                </p>
              </li>
            </ul>
          </div>
          <h3 className="text-3xl py-1 mt-10 dark:text-gray-100">
            My projects
          </h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web1"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web2"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web3"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web4"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web5"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web6"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
